version: "4.3"

services:
    survey_fe-app:
        build:
            context: "."
        container_name: survey_fe-app
        ports:
            - 8086:8086
        networks:
            backend:
                aliases:
                    - app

networks:
    backend:
        name: survey_fe-network